require('dotenv').config(); // ✨ PR: tiny non-functional change

const express = require("express");
const fs = require("fs");
const nodemailer = require("nodemailer");
const cron = require("node-cron");

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static("public")); // for HTML + JS + CSS

// Transporter (dummy, you can configure your Gmail)
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS
  }
});

// ===== DATA FUNCTIONS =====
function readData() {
  return JSON.parse(fs.readFileSync("members.json", "utf-8"));
}

function saveData(data) {
  fs.writeFileSync("members.json", JSON.stringify(data, null, 2));
}

// ===== ROUTES =====
app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

app.get("/data", (req, res) => {
  res.send(readData());
});

// Preview endpoint: generates an LLM-based message without sending an email.
// This route is used to test and preview the dynamic AI-generated message
// instead of the old static email content. It reads optional query params
// (name, recipientName), generates the message, and returns it as JSON
// so developers can verify the output before triggering the actual email flow.
app.get('/preview-message', async (req, res) => {
  const name = req.query.name || 'Alex';
  const recipientName = req.query.recipientName || 'Friend';
  const birthdayPerson = { name };
  const recipient = { name: recipientName };
  const message = await generateBirthdayMessage(birthdayPerson, recipient);
  // indicate this was generated by the (local) LLM-like generator
  res.json({ message, usedLLM: true });
});

app.post("/add-solo", (req, res) => {
  const data = readData();
  data.solo.push({
    name: req.body.name,
    birthday: req.body.birthday,
    email: req.body.email
  });
  saveData(data);
  res.send("Solo member added!");
});

app.post("/add-group", (req, res) => {
  const data = readData();
  const group = {
    groupName: req.body.groupName,
    members: req.body.members
  };
  data.groups.push(group);
  saveData(data);
  res.send("Group added!");
});

app.post("/save-all", (req, res) => {
  fs.writeFileSync("members.json", JSON.stringify(req.body, null, 2));
  res.send("updated");
});


app.post("/delete-solo", (req, res) => {
  const data = readData();
  data.solo.splice(req.body.index, 1);
  saveData(data);
  res.send("Deleted");
});

// Delete group
app.post("/delete-group", (req, res) => {
  const data = readData();
  data.groups.splice(req.body.index, 1);
  saveData(data);
  res.send("Deleted");
});

// Delete group member
app.post("/delete-group-member", (req, res) => {
  const data = readData();
  const gIndex = req.body.gIndex;
  const mIndex = req.body.mIndex;
  data.groups[gIndex].members.splice(mIndex, 1);
  saveData(data);
  res.send("Deleted");
});

// Local 'LLM-like' birthday message generator — supports two signatures:
//  - generateBirthdayMessage(name, mode)
//  - generateBirthdayMessage(birthdayPersonObj, recipientObj)
function generateBirthdayMessage(nameOrObj, modeOrRecipient = 'self') {
  // normalize inputs so existing calls remain compatible
  let name = 'Friend';
  let mode = 'self';

  if (typeof nameOrObj === 'object' && nameOrObj !== null) {
    const birthdayPerson = nameOrObj;
    name = birthdayPerson.name || name;

    if (typeof modeOrRecipient === 'object' && modeOrRecipient !== null) {
      const recipient = modeOrRecipient;
      // determine mode: if recipient is the same person, assume 'self', otherwise 'notify'
      mode = recipient.name && recipient.name === birthdayPerson.name ? 'self' : 'notify';
    } else {
      mode = typeof modeOrRecipient === 'string' ? modeOrRecipient : 'self';
    }
  } else {
    name = nameOrObj || name;
    mode = typeof modeOrRecipient === 'string' ? modeOrRecipient : 'self';
  }

  const variants = {
    self: [
      `Happy birthday, ${name}! Wishing you a wonderful day filled with joy 🎉`,
      `Hey ${name} — happy birthday! Hope it's amazing 🥳`,
      `Happy Birthday ${name}! Celebrate and enjoy your day 🎂`
    ],
    notify: [
      `Heads up — today is ${name}'s birthday! Send them your best wishes 🎉`,
      `Today is ${name}'s birthday. Consider sending a greeting 🥳`,
      `${name} celebrates a birthday today — drop them a message 🎂`
    ]
  };

  const arr = variants[mode] || variants.self;
  return arr[Math.floor(Math.random() * arr.length)];
}

// ===== BIRTHDAY EMAILS =====
function sendBirthdayEmails() {
  const data = readData();
  const today = new Date();
  const todayStr = `${today.getMonth() + 1}-${today.getDate()}`;

  // solo members
  data.solo.forEach(member => {
    const bday = new Date(member.birthday);
    const bdayStr = `${bday.getMonth() + 1}-${bday.getDate()}`;
    if (bdayStr === todayStr) {
      transporter.sendMail({
        from: "yourgmail@gmail.com",
        to: member.email,
        subject: "Birthday Reminder 🎉🎂",
        text: generateBirthdayMessage(member.name, 'self')
      });
    }
  });

  // group members
  data.groups.forEach(group => {
    group.members.forEach(birthdayMember => {
      const bday = new Date(birthdayMember.birthday);
      const bdayStr = `${bday.getMonth() + 1}-${bday.getDate()}`;
      if (bdayStr === todayStr) {
        group.members.forEach(other => {
          if (other.email !== birthdayMember.email) {
            transporter.sendMail({
              from: "yourgmail@gmail.com",
              to: other.email,
              subject: "Birthday Reminder 🎉🎂",
              text: generateBirthdayMessage(birthdayMember.name, 'notify')
            });
          }
        });
      }
    });
  });

  console.log("Birthday check completed.");
}

// run every midnight
cron.schedule("0 21 * * *", sendBirthdayEmails);

app.listen(PORT, () => console.log(`Server running at http://localhost:${PORT}`));


